devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Models/AuctionListModel.cs
using devAkademi.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace devAkademi_HEnesGokdag.Models
{
    public class AuctionListModel
    {
      public  List<Auction> Auctions { get; set; }
      public string SelectedCategory { get; set; }
    }
}

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Models/AuctionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace devAkademi_HEnesGokdag.Models
{
    public class AuctionModel
    {
        public long id { get; set; }
        public string title { get; set; }

        public string description { get; set; }

        public double price { get; set; }

        public int has_promotion { get; set; }

        public int view_count { get; set; }

        public string city { get; set; }

        public string town { get; set; }

        public string c0 { get; set; }

        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public string c4 { get; set; }
        public string c5 { get; set; }
        public string c6 { get; set; }
    }
}

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Models/CategoryListModel.cs
using devAkademi.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace devAkademi_HEnesGokdag.Models
{
    public class CategoryListModel
    {
        public string SelectedCategory { get; set; }
        public List<Category> Categories { get; set; }
    }
}

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Models/ErrorViewModel.cs
using System;

namespace devAkademi_HEnesGokdag.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using devAkademi_HEnesGokdag.Models;
using devAkademi.DataAccess;
using devAkademi.DataAccess.Abstract;

namespace devAkademi_HEnesGokdag.Controllers
{
    public class HomeController : Controller
    {
        private IWebServiceDal _read;
        public HomeController(IWebServiceDal read)
        {
            _read = read;
        }
         
        public IActionResult Index()
        {
            List<Auction> auctions = _read.LoadJsonsPagination(0, _read.AuctionSize());
            return View(new AuctionListModel()
            {
                Auctions = auctions
            });
        }

       
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult AuctionDetails(int id)
        {
            //id değerine göre ilan detayına ulaştığımız action
          Auction auction=  _read.LoadJsonFindById(id);
            if(auction==null)
            {
                return RedirectToAction("Index");
            }
            return View(new AuctionModel() {
                id=auction.id,
                title= auction.title,
                description = auction.description,
                price = auction.price,
                has_promotion = auction.has_promotion,
                view_count = auction.view_count,
                city= auction.city,
                town = auction.town,
                c0 = auction.c0,
                c1= auction.c1,
                c2 = auction.c2,
                c3 = auction.c3,
                c4 = auction.c4,
                c5 = auction.c5,
                c6 = auction.c6
                
            });
        }
        public IActionResult AuctionList(int id=0)
        {
            //sayfa bilgisi değerine göre ilan listesine ulaştığımız action
            int count = _read.AuctionsCount();
            int size = _read.AuctionSize();
            
            ViewBag.id = id;
            int pagesCount = count / size;
            int[] pages = new int[pagesCount+1];
            for (int i = 1; i <= pagesCount+1; i++)
            {
                pages[i-1] = i;
            }
            List<Auction> auctions=new List<Auction>();
            ViewBag.pages = pages;
            if(id!=0)
            {
                 auctions = _read.LoadJsonsPagination(id-1, _read.AuctionSize());
            }
            
            if (id == 0)
            {
                ViewBag.id = 1;
                 auctions = _read.LoadJsonsPagination(id, _read.AuctionSize());
            }
               
            return View(new AuctionListModel() {
                Auctions= auctions
            });
        }
        public IActionResult AuctionsByCategory(string category)
        {
            //gelen kategori bilgisine göre o kategoriyle ilişkili ilanların gösterildiği action
            List<Auction> auctions = _read.LoadAuctionsByCategory(category);
            ViewBag.count = auctions.Count;
            return View(new AuctionListModel()
            {
                Auctions = auctions,
                
                SelectedCategory = category
            });
        }
        public IActionResult AuctionsMostClicked()
        {
            //en çok bakılan 10 ilanın gösterildiği action
            List<Auction> auctions = _read.MostClickedAuctions();
            return View(new AuctionListModel()
            {
                Auctions = auctions
            });
        }
        [HttpPost]
        public IActionResult AuctionSearch(string searchedWord)
        {
            //gelen string bilgiye göre ilişkili title ve descriptionların bulunduğu ilanların gösterildiği action
            List<Auction> auctions = _read.SearchAuction(searchedWord);
            ViewBag.count = auctions.Count;
            return View(new AuctionListModel()
            {
                Auctions = auctions
            });
        }
    }
}

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/ViewComponents/CategoryListViewComponent.cs
using devAkademi.DataAccess;
using devAkademi.DataAccess.Abstract;
using devAkademi_HEnesGokdag.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace devAkademi_HEnesGokdag.ViewComponents
{
    public class CategoryListViewComponent :ViewComponent
    {
        private IWebServiceDal _read;
       
        public CategoryListViewComponent(IWebServiceDal read)
        {
            _read = read;
        }
        public IViewComponentResult Invoke()
        {
            var queryString = Request.Query["category"];
            string s = RouteData.Values["category"]?.ToString();
            return View(new CategoryListModel()
            {
                SelectedCategory = queryString.ToString(),
                Categories = _read.LoadJsonCategories()
            });
        }
    }
}

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Views/Home/AuctionDetails.cshtml
@model AuctionModel

@{
    ViewData["Title"] = Model.title;
}

<h1>@Model.title</h1>

<div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="AuctionsByCategory" asp-route-category="@Model.c0">@Model.c0</a></li>

            <li class="breadcrumb-item active" aria-current="page">@Model.c1</li>
            <li class="breadcrumb-item active" aria-current="page">@Model.c2</li>
            <li class="breadcrumb-item active" aria-current="page">@Model.c3</li>


            @if (Model.c4 != null)
            {
                <li class="breadcrumb-item active" aria-current="page">@Model.c4</li>
            }
            @if (Model.c5 != null)
            {
                <li class="breadcrumb-item active" aria-current="page">@Model.c5</li>
            }
            @if (Model.c6 != null)
            {
                <li class="breadcrumb-item active" aria-current="page">@Model.c6</li>
            }
        </ol>
    </nav>
    <hr />
    <div class="row">
        <div class="col-sm-2 offset-md-2"><p class="text-black-50">Başlık:</p>  </div>
        <div class="col-md-8"> <p>@Html.DisplayFor(model => model.title) </p></div>

    </div>
    <div class="row">
        <div class="col-sm-2 offset-md-2"><p class="text-black-50">Açıklama:</p>  </div>
        <div class="col-md-8"> @Html.Raw(Model.description) </div>

    </div>
    <div class="row">
        <div class="col-sm-2 offset-md-2"><p class="text-black-50">Ücret:</p>  </div>
        <div class="col-md-8"> <p>@Html.DisplayFor(model => model.price) </p></div>

    </div>
    <div class="row">
        <div class="col-sm-2 offset-md-2"><p class="text-black-50">İlan Gösterilme Sayısı:</p>  </div>
        <div class="col-md-8"> <p>@Html.DisplayFor(model => model.view_count) </p></div>

    </div>
    <div class="row">
        <div class="col-sm-2 offset-md-2"><p class="text-black-50">Şehir:</p>  </div>
        <div class="col-md-8"> <p>@Html.DisplayFor(model => model.city) </p></div>

    </div>
    <div class="row">
        <div class="col-sm-2 offset-md-2"><p class="text-black-50">İlçe:</p>  </div>
        <div class="col-md-8"> <p>@Html.DisplayFor(model => model.town) </p></div>

    </div>
    
</div>

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Views/Home/AuctionList.cshtml
@model devAkademi_HEnesGokdag.Models.AuctionListModel

@{
    ViewData["Title"] = "AuctionList";
}

<div class="row mt-5">

    <div class="col-md-3">

        @await Component.InvokeAsync("CategoryList")

    </div>
    <div class="col-md-9">
        @foreach (var item in Model.Auctions)
        {


            <div class="card mb-3">
                <div class="row no-gutter">
                    <div class="col-md-3">
                        <img src="https://via.placeholder.com/150" class="card-img" />
                    </div>
                    <div class="col-md-9">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a asp-action="AuctionDetails" asp-controller="Home" asp-route-id="@item.id">  @item.title</a>
                            </h5>
                            <p class="card-text">
                                <small class="text-muted">Kategori: <a asp-controller="Home" asp-action="AuctionsByCategory" asp-route-category="@item.c0">@item.c0</a> </small>
                            </p>
                            <p class="card-text">
                                @Html.Raw(item.description.Length > 100 ? item.description.Substring(0, 100) + "..." : item.description)
                            </p>
                            <p class="card-text">
                                <small class="text-muted">Ücret: @item.price ₺</small>
                            </p>
                            <a  asp-action="AuctionDetails" asp-controller="Home" asp-route-id="@item.id" class="btn btn-primary float-right mb-2">İlana Git</a>
                        </div>
                    </div>
                </div>

            </div>


        }
         </div>

    </div>
    <div>
        <ul class="pagination">
            @foreach (var item in ViewBag.Pages)
            {
                <li class="page-item @((ViewBag.id==item)?"active":"")">
                    <a class='page-link' href='/Home/AuctionList/@item'>@item</a>
                </li>
            }
        </ul>
    </div>

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Views/Home/AuctionSearch.cshtml
@model devAkademi_HEnesGokdag.Models.AuctionListModel
@{
    ViewData["Title"] = "AuctionSearch";
}

<div>

    @if (ViewBag.count != 0)
    {
        <div class="alert alert-primary" role="alert">
            <i class="fas fa-check"></i>  Arama Sonucunda @ViewBag.Count Tane İlan Bulundu.
        </div>
    }
    else
    {
        <div class="alert alert-danger" role="alert">
            <i class="fas fa-exclamation-triangle"></i>  Arama Sonucunda İlan Bulunamadı.
        </div>
    }
    <div class="row">
        <div class="col-md-3">

            @await Component.InvokeAsync("CategoryList")

        </div>
        <div class="col-md-9">


            @foreach (var item in Model.Auctions)
            {


                <div class="card mb-3">
                    <div class="row no-gutter">
                        <div class="col-md-3">
                            <img src="https://via.placeholder.com/150" class="card-img" />
                        </div>
                        <div class="col-md-9">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a asp-action="AuctionDetails" asp-asp-controller="Home" asp-route-id="@item.id">  @item.title</a>
                                </h5>
                                <p class="card-text">
                                    <small class="text-muted">Kategori: <a asp-controller="Home" asp-action="AuctionsByCategory" asp-route-category="@item.c0">@item.c0</a> </small>
                                </p>

                                <p class="card-text">
                                    @Html.Raw(item.description.Length > 100 ? item.description.Substring(0, 100) + "..." : item.description)
                                </p>
                                <p class="card-text">
                                    <small class="text-muted">Ücret: @item.price ₺</small>
                                </p>
                                <a asp-action="AuctionDetails" asp-asp-controller="Home" asp-route-id="@item.id" class="btn btn-primary float-right mb-2">İlana Git</a>
                            </div>
                        </div>
                    </div>

                </div>


            }
        </div>
    </div>
</div>

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Views/Home/AuctionsByCategory.cshtml
@model devAkademi_HEnesGokdag.Models.AuctionListModel

@{
    ViewData["Title"] = "AuctionsByCategory";
}
<div>

    @if (ViewBag.count != 0)
    {
        <div class="alert alert-primary" role="alert">
            <i class="fas fa-check"></i>  Kategoride Toplam @ViewBag.Count Tane İlan Var.
        </div>
    }
    else
    {
        <div class="alert alert-danger" role="alert">
            <i class="fas fa-exclamation-triangle"></i>  Kategoride Ürün Bulunmamaktadır.
        </div>
    }
    <div class="row">
        <div class="col-md-3">

            @await Component.InvokeAsync("CategoryList")

        </div>
        <div class="col-md-9">


            @foreach (var item in Model.Auctions)
            {


            <div class="card mb-3">
                <div class="row no-gutter">
                    <div class="col-md-3">
                        <img src="https://via.placeholder.com/150" class="card-img" />
                    </div>
                    <div class="col-md-9">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a asp-action="AuctionDetails" asp-controller="Home" asp-route-id="@item.id">  @item.title</a>
                            </h5>
                            <p class="card-text">
                                <small class="text-muted">Kategori: <a asp-controller="Home" asp-action="AuctionsByCategory" asp-route-category="@item.c0">@item.c0</a> </small>
                            </p>
                            
                            <p class="card-text">
                                @Html.Raw(item.description.Length>100?item.description.Substring(0,100)+"...":item.description)
                            </p>
                            <p class="card-text">
                                <small class="text-muted">Ücret: @item.price ₺</small>
                            </p>
                            <a asp-action="AuctionDetails" asp-controller="Home" asp-route-id="@item.id" class="btn btn-primary float-right mb-2">İlana Git</a>
                        </div>
                    </div>
                </div>

            </div>


            }
        </div>
    </div>
</div>

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Views/Home/AuctionsMostClicked.cshtml
@model devAkademi_HEnesGokdag.Models.AuctionListModel
@{
    ViewData["Title"] = "AuctionsMostClicked";
}

<h3 class="text-center">En Çok Tıklanan 10 İlan</h3>
<hr />
<div class="row">
    <div class="col-md-3">

        @await Component.InvokeAsync("CategoryList")

    </div>
    <div class="col-md-9">
        @foreach (var item in Model.Auctions)
        {

        <div class="card mb-3">
            <div class="row no-gutter">
                <div class="col-md-3">
                    <img src="https://via.placeholder.com/150" class="card-img" />
                </div>
                <div class="col-md-9">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a asp-action="AuctionDetails" asp-controller="Home" asp-route-id="@item.id">  @item.title</a>
                        </h5>
                        <p class="card-text">
                            <small class="text-muted">Kategori: <a asp-controller="Home" asp-action="AuctionsByCategory" asp-route-category="@item.c0">@item.c0</a> </small>
                        </p>
                        <p class="card-text">
                            @Html.Raw(item.description.Length > 100 ? item.description.Substring(0, 100) + "..." : item.description)
                        </p>
                        <p class="card-text">
                            <small class="text-muted">Ücret: @item.price ₺</small>
                        </p>
                        <a asp-action="AuctionDetails" asp-controller="Home" asp-route-id="@item.id" class="btn btn-primary float-right mb-2">İlana Git</a>
                    </div>
                </div>
            </div>

        </div>

        }
    </div>
</div>

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Views/Home/Index.cshtml
@model devAkademi_HEnesGokdag.Models.AuctionListModel

@{
    ViewData["Title"] = "Home Page";
}


<div class="row pt-5">
    <div class="col-md-3">

        @await Component.InvokeAsync("CategoryList")

    </div>
    <div class="col-md-9">
        <partial name="_slider" />
        @foreach (var item in Model.Auctions)
        {
            
        <div class="card mb-3">
            <div class="row no-gutter">
                <div class="col-md-3">
                    <img src="https://via.placeholder.com/150" class="card-img" />
                </div>
                <div class="col-md-9">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a asp-action="AuctionDetails" asp-controller="Home" asp-route-id="@item.id">  @item.title</a>
                        </h5>
                        <p class="card-text">
                            <small class="text-muted">Kategori: <a asp-controller="Home" asp-action="AuctionsByCategory" asp-route-category="@item.c0">@item.c0</a> </small>
                        </p>
                        <p class="card-text">
                            @Html.Raw(item.description.Length > 100 ? item.description.Substring(0, 100) + "..." : item.description)
                        </p>
                        <p class="card-text">
                            <small class="text-muted">Ücret: @item.price ₺</small>
                        </p>
                        <a asp-action="AuctionDetails" asp-controller="Home" asp-route-id="@item.id" class="btn btn-primary float-right mb-2">İlana Git</a>
                    </div>
                </div>
            </div>

        </div>
             
        }
    </div>
</div>

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListModel

@foreach (var item in Model.Categories)
{
    
    <ul class="list-group">
        <li class="list-group-item   @(Model.SelectedCategory==item.CategoryName?"list-group-item-action active":"")">
            <a asp-controller="Home" asp-action="AuctionsByCategory" asp-route-category="@item.CategoryName">@item.CategoryName </a></li>

    </ul>
}

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - devAkademi_HEnesGokdag</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <partial name="_navbar" />
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_footer" />

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>

    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Views/Shared/_footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2019 - devAkademi_HEnesGokdag
    </div>
</footer>

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-dark bg-primary navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sahibinden</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse ">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="AuctionList">İlan Listesi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="AuctionsMostClicked">En Çok Tıklanan İlanlar</a>
                </li>
            </ul>
            @using (Html.BeginForm("AuctionSearch", "Home", FormMethod.Post, new { @class = "form-inline my-2 my-lg-0" }))
            {
                <input class="form-control mr-sm-2" name="searchedWord" type="search" placeholder="Ara" aria-label="Search">
                <button class="btn btn-success my-2 my-sm-0"  type="submit">İlan Ara</button>

            }
            
        </div>
    </div>
</nav>

devAkademi_HEnesGokdag/devAkademi_HEnesGokdag/Views/Shared/_slider.cshtml
<div id="mySlider" class="carousel slide mb-3" data-ride="carousel">

    <ol class="carousel-indicators">
        <li data-target="#mySlider" data-slide-to="0" class="active"></li>
        <li data-target="#mySlider" data-slide-to="1"></li>
        <li data-target="#mySlider" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">

            <img src="https://via.placeholder.com/1200x365" class="d-block img-fluid" />

        </div>
        <div class="carousel-item">

            <img src="https://via.placeholder.com/1200x365" class="d-block img-fluid" />

        </div>
        <div class="carousel-item">

            <img src="https://via.placeholder.com/1200x365" class="d-block img-fluid" />

        </div>
    </div>
    <a href="#mySlider" data-slide="prev" class="carousel-control-prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a href="#mySlider" data-slide="next" class="carousel-control-next">
        <span class="carousel-control-next-icon"></span>
    </a>
</div>